version: '3'
services: 
 magic-card-service:
  restart: on-failure
  build:
   context: ./
   dockerfile: Dockerfile.dev
  ports:
   - "8080:8080"
  environment:
   - env.deploy =local
  extra_hosts:
    - "host.docker.internal:host-gateway"