name: Deploy magic-card-service
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vineelpellella/magic-card-service -f ./Dockerfile .
 
      - run: docker build -t vineelpellella/magic-card-service .

 
      - run: docker push vineelpellella/magic-card-service

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: magic-card-service
          environment_name: Magiccardservice-env-1
          existing_bucket_name: elasticbeanstalk-us-west-1-423357185755
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
